### ISSUE TITLE
ImageCheck.isVoxelIsotropic checks pixel dimensions incorrectly

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#1]
Found a bug in isVoxelIsoTropic while running the following test code:

```
pixelWidth = 2;
pixelHeight = 1;
pixelDepth = 1000;
...
boolean result = ImageCheck.isVoxelIsotropic(testImage, 1.0);
assertFalse("Pixel depth too great to be anisotropic within tolerance", result)
```

The assertion failed.

**Comment by mdoube** [comment]
@rimadoma Was this issue closed with the commits from yesterday? If so I will close it.

**Comment by rimadoma** [comment]
@mdoube It was fixed on Monday's pull-request (issue1). In any case, you can close it.

**Comment by mdoube** [comment]
OK, closing.
