### ISSUE TITLE
VolumeFraction show3D breaks ImageJ UI

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#22]
After running the _VolumeFraction_ plugin with options _algorithm = surface_ and _show 3D result = true_ the ImageJ UI breaks down. For example, if you try to rerun the plugin, the dialog is transparent, e.g. only it's frames are visible. The issue probably lies in the implementation of _3D Viewer_, but it affects BoneJ as well.

**Comment by mdoube** [comment]
Can you reproduce this on another OS? Sometimes I see this kind of thing and put it down to display drivers / Java / something generally out of my control.

**Comment by rimadoma** [comment]
Issue first encountered  with:
Ubuntu Kylin 14.04 64-bit
NVidia GF119 version 340.96
Java 1.8.0_72
ImageJ 1.50e

**Comment by rimadoma** [comment]
@mdoube The bug _didn't_ appear on Alessandro's Windows laptop:
Windows 7
NVidia drivers
Java 1.6.0_24
ImageJ 1.50e

The difference might be explained by different Java versions

**Comment by mdoube** [comment]
I'm pretty sure this is an Ubuntu window manager / Java for Linux issue.
