### ISSUE TITLE
Fit Ellipsoid reports a "NaN" radius

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#32]
The Results table shows "Radius 1" as "NaN" when point ROIs are close on the xy-plane.

Steps to reproduce:
1. Open bundled bone sample (_File > Open Samples > Bat Cochlea Volume_)
2. Select slide 3
3. Select point tool
4. Draw a point ROI on the white area
5. Press _T_ to add the point to ROI manager
6. Select next slide.
7. Return to step 4 until you have 9 points on 9 consecutive slides (place the points roughly on the same xy-coordinates)
8. Run Fit Ellipsoid (_Plugins > BoneJ > Fit Ellipsoid_)

**Comment by rimadoma** [comment]
This is caused by the fact that the "yuryPetrov" ellipsoid fitting used in BoneJ does not guarantee that the result is an ellipsoid. In fact, it just solves the quadric that best fits the points. It may be any quadric: such as a cone, hyperboloid or a set of parallel planes.

You can determine the type of quadric from the eigenvalues of the quadric, or the the values on the diagonal of the matrix. If a, b, c are all positive, it's an ellipsoid(<img src="http://www.sciweavers.org/tex2img.php?eq=%20%5Cfrac%7B%20x%5E%7B2%7D%20%7D%7B%20a%5E%7B2%7D%20%7D%20%20%2B%20%20%5Cfrac%7B%20y%5E%7B2%7D%20%7D%7B%20b%5E%7B2%7D%20%7D%20%20%2B%20%20%5Cfrac%7B%20z%5E%7B2%7D%20%7D%7B%20c%5E%7B2%7D%20%7D%20%3D%201&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt=" \frac{ x^{2} }{ a^{2} }  +  \frac{ y^{2} }{ b^{2} }  +  \frac{ z^{2} }{ c^{2} } = 1" width="142" height="46" />). Thus after calling the method, you should check if it's an ellipsoid, and display an error if it's not.

**Comment by rimadoma** [comment]
Also these are not really issues, but it could be worth mentioning in the comments that:
1) eigen vectors may form a left-handed basis.
2) The inverse of the design matrix being solved is most often a pseudoinverse matrix.

**Comment by mdoube** [comment]
Fixed in https://github.com/mdoube/BoneJ/commit/56b600a8bb630a766b72ffc00020c94cb3e37b8a
