### ISSUE TITLE
ParticleCounter: fallthrough in `switch` statement

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#39]
A `case` block in ParticleCounter is missing the `break;` line at https://github.com/bonej-org/bonej/blob/e2c43dbcb75d0e97205e45ba907d1e5d8a816972/src/org/doube/bonej/ParticleCounter.java#L1855. Is this intended behaviour?

**Comment by mdoube** [comment]
Fixed by https://github.com/mdoube/BoneJ/commit/2a48fd31e7fac1391266669454c17f607158a1b5
